### ISSUE TITLE
Local SVG files

### ISSUE THREAD

**Issue by Sundin** [chitezh/react-native-svg-image#10]
Is it possible to load a local file instead of URL? If i download the dumbbell.svg (https://fluent-panda.appspot.com.storage.googleapis.com/dumbbell.svg) file from the example in the readme and tries to load it using `source={{uri: require('./dumbbell.svg')}}`, I get the following error:  `TypeError: invalid svg`.

Loading the SVG from the URL as in the example in the readme works just fine though.

**Comment by chitezh** [comment]
Sorry it only works for urls

**Comment by Sundin** [comment]
Thank you for your answer, good to know! Maybe should add it to the readme, the sentence _"Same kind of source prop that <Image /> component has"_ is a bit misleading, as Image can handle both url and local files.

Cheers!

**Comment by chitezh** [comment]
@Sundin You're right. It's really misleading
