### ISSUE TITLE
Images size regression with React Native 0.47.0

### ISSUE THREAD

**Issue by kytwb** [chitezh/react-native-svg-image#12]
Since we upgraded yesterday, our SVG images size has changed, see below.

![simulator screen shot 2 aug 2017 11 38 18 am](https://user-images.githubusercontent.com/412895/28870180-3894c43c-7777-11e7-8e0d-039ef8403ff9.png)

Will investigate and come up with a solution.

**Comment by chitezh** [comment]
@kytwb did you also upgrade react-native-svg-image?

**Comment by kytwb** [comment]
Oopsie 😅  Fixes it.

**Comment by kytwb** [comment]
Actually it's still happening. But not everytime. Sometimes it displays the right size, sometimes not. Will try to investigate, but it seems very random. Just happened to me the image was the right size, was working on something else, hot reload kicks in, image is not the right size anymore.

**Comment by kytwb** [comment]
If I had `scalesPageToFit={false}` it seems to work.

**Comment by chitezh** [comment]
Nice! we'd add that to the readme or make it a default behavior.

@kytwb Could you make a PR for that?

**Comment by kytwb** [comment]
This was probably a regression introduced by https://github.com/facebook/react-native/pull/14363.
