### ISSUE TITLE
Unable to show local svg image

### ISSUE THREAD

**Issue by ashwingattani** [chitezh/react-native-svg-image#15]
Hello,

I am trying to load a local svg image using SVGImage tag, but it shows a faint box instead of the actual image. The same image works fine if loaded from a server url.

Can you please help me out here. I need to show local images in my application. Following is the code snippet i am working on : 

```
<View style={{ flex: 1 }}>
        <SVGImage
          style={{ width: 80, height: 80 }}
          source={{uri:'./dumbbell.svg'}}
        />
</View>
```

**Output:**

![svg_output](https://user-images.githubusercontent.com/9816850/30125718-f98ed5b0-9356-11e7-8f24-306798b13f57.png)

Thanks in advance! 😄

**Comment by chitezh** [comment]
It does not work with local svg files at the moment

**Comment by ashwingattani** [comment]
ah too bad! any update when it could be handled?

**Comment by chitezh** [comment]
I'm not using actively working on this atm
