### ISSUE TITLE
Margin on SVG

### ISSUE THREAD

**Issue by DiegoGallegos4** [chitezh/react-native-svg-image#7]
![image](https://user-images.githubusercontent.com/5933437/27358826-ac87621e-55d5-11e7-9c56-b16279475bab.png)
There is a margin around the image. Already tried setting padding and margin to 0 but no success. Can you bring more insight to this issue?

version: 1.1.3
react-native-svg version: 5.1.8

**Comment by chitezh** [comment]
Thanks Diego, Could you confirm the version of the package that you are using?

**Comment by chitezh** [comment]
Thanks @DiegoGallegos4 Could you confirm the version you are using?

**Comment by DiegoGallegos4** [comment]
@chitezh already edited the issue with the versions.

**Comment by chitezh** [comment]
could try modifying the package `node_modules/react-native-svg-image`? 
```
    const html = `
      <!DOCTYPE html>\n
      <html>
        <head>
          <style type="text/css">
            img {
              width: 100%;
              height: 100%;
              margin: 0 auto;
            }
            div {
              width: ${width ? width+'px' : 'auto'};
              height: ${height ? height+'px' : 'auto'};
              margin: 0;
            }
            body {
              margin: 0;
            }
          </style>
        </head>
        <body>
          <div>
            <img src="${uri}" align="middle" />
          </div>
        </body>
      </html>
    `;```

I added margin to div

**Comment by DiegoGallegos4** [comment]
@chitezh No its not working.

**Comment by chitezh** [comment]
Strange! Is this happening with all the images?

One more thing you could try is also set padding to 0. 
Also, note that you have to restart the package after editing `/node_modules/*`

**Comment by DiegoGallegos4** [comment]
@chitezh Yes I have made other changes to know if it updating but those changes are not working. I have tried doing a global reset (padding and margin 0 to *).

**Comment by chitezh** [comment]
Try setting `body` backgroundColor to red

**Comment by DiegoGallegos4** [comment]
I have added border to html > body > div. 
![image](https://user-images.githubusercontent.com/5933437/27359955-dfebfcc2-55db-11e7-9ac7-e86c4ccb077c.png)

This is background-color red to body. 

![image](https://user-images.githubusercontent.com/5933437/27359968-f43f0f16-55db-11e7-815a-f1a833965627.png)

**Comment by chitezh** [comment]
could you set height and width in style?

**Comment by DiegoGallegos4** [comment]
I applied to WebView and body. Height is not applied.
![image](https://user-images.githubusercontent.com/5933437/27360145-c59c253a-55dc-11e7-8ebe-8102c6e7565f.png)

**Comment by chitezh** [comment]
I meant like 
```<SVGImage
      style={{ width: 80, height: 80 }}
      source={{uri:'https://fluent-panda.appspot.com.storage.googleapis.com/dumbbell.svg'}}
    />```

**Comment by chitezh** [comment]
I'm kinda sleepy, I'll look at this once I get up.
When you're able to get a fix, please, make a fork of the repo and continue from there so I don't block you

**Comment by DiegoGallegos4** [comment]
Yes that has been since the start. I'll give it a few more tries.

![image](https://user-images.githubusercontent.com/5933437/27360484-9a1027e8-55de-11e7-9efd-b9da8bfaea1c.png)
